sudo: false
rvm:
    - "1.8.7"
    - "1.9.3-p551"
    - "2.0.0-p648"
    - "2.1.10"
    - "2.2.5"
    - "2.3.1"
    - "jruby-1.7.26"
    - "jruby-9.1.5.0"
# 2016-09-20 ageweke -- This is temporary, and is because JRuby 1.7.26 is incompatible with Bundler 1.13.0/1,
# because of the following issue: https://github.com/bundler/bundler/issues/4975.
before_install:
    - ruby .fix_bundler_for_jruby_17
env:
    - FORTITUDE_SPECS_RAILS_VERSION=5.0.0.1
    - FORTITUDE_SPECS_RAILS_VERSION=4.2.7.1
    - FORTITUDE_SPECS_RAILS_VERSION=4.1.16
    - FORTITUDE_SPECS_RAILS_VERSION=4.0.13
    - FORTITUDE_SPECS_RAILS_VERSION=3.2.22.5
    - FORTITUDE_SPECS_RAILS_VERSION=3.1.12
    - FORTITUDE_SPECS_RAILS_VERSION=3.0.20
    - FORTITUDE_NATIVE_EXTENSIONS=false FORTITUDE_SPECS_RAILS_VERSION=4.2.7.1
    - FORTITUDE_NATIVE_EXTENSIONS=false FORTITUDE_SPECS_RAILS_VERSION=3.0.20
matrix:
    exclude:
        # Rails 4.x doesn't support Ruby 1.8.7
        -   rvm: 1.8.7
            env: FORTITUDE_SPECS_RAILS_VERSION=4.2.7.1
        -   rvm: 1.8.7
            env: FORTITUDE_SPECS_RAILS_VERSION=4.1.16
        -   rvm: 1.8.7
            env: FORTITUDE_NATIVE_EXTENSIONS=false FORTITUDE_SPECS_RAILS_VERSION=4.2.7.1
        -   rvm: 1.8.7
            env: FORTITUDE_SPECS_RAILS_VERSION=4.0.13
        # Rails 5.x doesn't support Ruby < 2.2
        -   rvm: 1.8.7
            env: FORTITUDE_SPECS_RAILS_VERSION=5.0.0.1
        -   rvm: "1.9.3-p551"
            env: FORTITUDE_SPECS_RAILS_VERSION=5.0.0.1
        -   rvm: "2.0.0-p648"
            env: FORTITUDE_SPECS_RAILS_VERSION=5.0.0.1
        -   rvm: "2.1.10"
            env: FORTITUDE_SPECS_RAILS_VERSION=5.0.0.1
        -   rvm: "jruby-1.7.26"
            env: FORTITUDE_SPECS_RAILS_VERSION=5.0.0.1
        # JRuby doesn't support Rails 5 yet
        -   rvm: jruby-9.1.5.0
            env: FORTITUDE_SPECS_RAILS_VERSION=5.0.0.1
